const steps=[...document.querySelectorAll('.step')],personNodes=[...document.querySelectorAll('[data-person]')];
let current=0,name='',acks=[];
const pad=n=>String(n).padStart(2,'0');
function indiaTime(){return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())+' IST'}
function updateTime(){document.querySelector('#live-time').textContent=indiaTime()}updateTime();setInterval(updateTime,1000);
function updatePerson(){personNodes.forEach(node=>node.textContent=name||'FOUNDING LEARNER')}
function show(index){if(index<0||index>=steps.length)return;steps[current].classList.remove('active');current=index;steps[current].classList.add('active');document.querySelector('#current-step').textContent=pad(current+1);document.querySelector('#step-name').textContent=steps[current].dataset.title.toUpperCase();document.querySelector('#progress-fill').style.width=`${(current+1)/steps.length*100}%`;document.querySelector('#previous').disabled=current===0;document.querySelector('#next').disabled=current===0||current===steps.length-1;if(current===9){document.querySelector('#completion-time').textContent=indiaTime();document.querySelector('#ack-total').textContent=`${acks.length} / 8`}}
document.querySelector('#name-form').addEventListener('submit',event=>{event.preventDefault();const value=document.querySelector('#name').value.trim();if(!value){document.querySelector('#name-hint').textContent='Please enter your name to continue.';return}name=value;updatePerson();show(1)});
document.querySelectorAll('.ack').forEach(button=>button.addEventListener('click',()=>{const entry=button.dataset.ack;if(!acks.includes(entry))acks.push(entry);show(current+1)}));
document.querySelector('#previous').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);
document.addEventListener('keydown',event=>{if(event.key==='ArrowRight'||event.key===' '){event.preventDefault();if(current>0)show(current+1)}if(event.key==='ArrowLeft'){event.preventDefault();show(current-1)}if(event.key==='Escape')exitOnboarding()});
function summary(){return `SARLAYASH BLESSINGS INTERNSHIPS 2026\nBATCH 01 ONBOARDING SUMMARY\n\nLearner: ${name||'Founding Learner'}\nCompleted: ${indiaTime()}\n\nACKNOWLEDGMENTS\n${acks.map((ack,i)=>`${i+1}. ${ack}`).join('\n')}\n\nSarlaYash Mission\nLegacy of Values. Future of Learning.`}
document.querySelector('#download').onclick=()=>{const blob=new Blob([summary()],{type:'text/plain'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`SarlaYash-Batch-01-${(name||'Learner').replace(/[^a-z0-9]/gi,'-')}-Summary.txt`;link.click();URL.revokeObjectURL(url)};
function exitOnboarding(){document.querySelector('#onboarding').hidden=true;document.querySelector('#exit-screen').hidden=false;try{window.close()}catch{}}
document.querySelector('#exit').onclick=exitOnboarding;document.querySelector('#exit-mini').onclick=exitOnboarding;document.querySelector('#return').onclick=()=>{document.querySelector('#exit-screen').hidden=true;document.querySelector('#onboarding').hidden=false;show(9)};
const canvas=document.querySelector('#dust'),ctx=canvas.getContext('2d');let specks=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;specks=Array.from({length:42},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.1+.15,v:Math.random()*.16+.025,a:Math.random()*.35+.08}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);for(const dot of specks){dot.y-=dot.v;if(dot.y<0)dot.y=canvas.height;ctx.fillStyle=`rgba(228,185,85,${dot.a})`;ctx.beginPath();ctx.arc(dot.x,dot.y,dot.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();show(0);
